@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor "Santa" as Santa
participant ":Parser" as Parser
participant "command:ChildListCommand" as ChildListCommand
participant "childList:ChildList" as childList
participant "currentChild:Child" as Child

Santa -> Parser : "childlist"
activate Parser

Parser -> Parser : parseCommand("childlist")

create ChildListCommand
Parser -> ChildListCommand : new ChildListCommand()

Parser -> ChildListCommand : execute()
activate ChildListCommand

opt childList is empty
    ChildListCommand --> Parser : "The child list is empty!"
else childList is not empty
    loop for each Child in childList
        ChildListCommand -> childList : get(i)
        activate childList
        childList --> ChildListCommand : currentChild
        deactivate childList

        ChildListCommand -> Child : toString()
        activate Child
        Child --> ChildListCommand : childString
        deactivate Child
    end
    ChildListCommand --> Parser : resultString
    deactivate ChildListCommand
end

Parser --> Santa : "Here are all children:\n..."
deactivate Parser

@enduml
