@startuml

participant "ClausControl" as App
participant Storage
participant File
participant Child
participant Gift
participant Elf
participant ElfTask as Task

App -> Storage : load()
Storage -> File : readLine()

loop for each line

    alt line starts with CHILD
        Storage -> Child : new Child(name, age, location)
        note right
        currentChild = Child
        currentElf = null
        end note
    end

    alt line starts with GIFT
        Storage -> Gift : new Gift(name)

        alt state == PREPARED
            Storage -> Gift : markPrepared()
        else state == DELIVERED
            Storage -> Gift : markDelivered()
        end

        Storage -> Child : addGift(gift)
    end

    alt line starts with ACTION
        Storage -> Child : addAction(description, severity)
    end

    alt line starts with ELF
        Storage -> Elf : new Elf(name)
        note right
        currentElf = Elf
        currentChild = null
        end note
    end

    alt line starts with TASK
        Storage -> Task : new Task(description)
        Storage -> Elf : addTask(task)
    end

end

Storage --> App : StorageData(children, elves)

@enduml