@startuml
Actor Santa
Santa -> Parser : todo d/Buy gifts by/2026-12-20
Parser -> AddTodoCommand : new AddTodoCommand(arguments, todoList)
AddTodoCommand -> AddTodoCommand : validate description
AddTodoCommand -> AddTodoCommand : validate deadline not in past
AddTodoCommand -> Todo : new Todo(description, deadline)
AddTodoCommand -> todoList : add(todo)
AddTodoCommand --> Santa : "Todo added: Buy gifts (due: 2026-12-20)"
@enduml