package seedu.clauscontrol;

import seedu.clauscontrol.commands.Command;
import seedu.clauscontrol.data.child.Child;
import seedu.clauscontrol.data.elf.Elf;
import seedu.clauscontrol.data.exception.IllegalValueException;
import seedu.clauscontrol.data.todo.Todo;
import seedu.clauscontrol.parser.Parser;
import seedu.clauscontrol.storage.TodoStorage;
import seedu.clauscontrol.ui.TextUi;

import seedu.clauscontrol.storage.Storage;
import java.io.IOException;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import seedu.clauscontrol.commands.FinalizeCommand;


//@@author shrabasti-c
// Solution below adapted from https://github.com/se-edu/addressbook-level2/blob
// /master/src/seedu/addressbook/Main.java
// with minor modifications
public class ClausControl {
    public static final String LOGO = "  .-\"\"-.\n" +
            " /,..___\\\n" +
            "() {_____}\n" +
            "  (/-@-@-\\)\n" +
            "  {`-=^=-'}\n" +
            "  {  `-'  } Welcome to ClausControl, Santa!\n" +
            "   {     }\n" +
            "    `---'\n";

    private static Logger logger = Logger.getLogger("Foo");

    //@@author GShubhan
    private boolean isFinalized = false;
    private ArrayList<Todo> todoList = new ArrayList<>();
    private TodoStorage todoStorage = new TodoStorage("todos.txt");

    //@@author

    private TextUi ui = new TextUi();
    private Parser parser;
    private ArrayList<Child> childList = new ArrayList<>();
    private ArrayList<Elf> elfList = new ArrayList<>();

    private Storage storage= new Storage("data.txt");



    //@@author shrabasti-c-reused
    //this function was generated by Claude
    public ClausControl() {
        this(System.in);
    }

    //this function was generated by Claude
    public ClausControl(InputStream inputStream) {
        this.ui = new TextUi(inputStream);
        //@@author prerana-r11
        try {
            this.childList = new ArrayList<>(storage.load());
        } catch (IOException e) {
            this.childList = new ArrayList<>();
        }
        //@@author
        //@@author GShubhan
        try {
            this.todoList = new ArrayList<>(todoStorage.load());
        } catch (IOException e) {
            this.todoList = new ArrayList<>();
        }
        this.parser = new Parser(todoList);  // initialize AFTER loading todos
    }
    //@@author
    //@@author

    /** Reads the user command and executes it, until the user issues the exit command.  */
    private void runCommandLoopUntilExitCommand() throws IllegalValueException {
        Command command;
        do {
            try {
                String userCommandText = ui.getUserCommand();
                if (userCommandText.equals("bye")) {
                    logger.log(Level.INFO, "end of processing");
                    return;
                }
                command = parser.parseCommand(userCommandText);
                command.setData(childList, elfList, isFinalized);
                //@@author GShubhan
                String result = command.execute();
                try {
                    storage.save(childList);
                } catch (IOException e) {
                    logger.warning("Error saving: " + e.getMessage());
                }
                if (command instanceof FinalizeCommand) {
                    isFinalized = true;
                }
                try {
                    todoStorage.save(todoList);
                } catch (IOException e) {
                    logger.warning("Error saving todos: " + e.getMessage());
                }

                System.out.println(result); //TODO: ui formatting required
                //@@author
            } catch (IllegalValueException e) {
                System.out.println(e.getMessage()); //TODO: ui formatting required
                logger.log(Level.INFO, "processing error");
            } catch(Exception e){
                return;
            }
        } while (true);
    }

    /** Runs the program until termination.  */
    public void run() throws IllegalValueException {
        System.out.println(LOGO);
        showUpcomingTodos();
        runCommandLoopUntilExitCommand();
        //System.exit(0);
    }
    //@@author GShubhan
    private void showUpcomingTodos() {
        StringBuilder sb = new StringBuilder();
        for (Todo todo : todoList) {
            if (todo.isUpcoming()) {
                sb.append("- ").append(todo.getDescription())
                        .append(" (due: ").append(todo.getDeadline()).append(")\n");
            }
        }
        if (sb.length() > 0) {
            System.out.println("Upcoming reminders this week:");
            System.out.println(sb.toString().trim());
            System.out.println();
        }
    }
    //@@author
    /**
     * Main entry-point for the ClausControl application.
     */
    public static void main(String[] args) throws IllegalValueException {
        Logger.getLogger("seedu.duke").setLevel(Level.WARNING);
        new ClausControl().run();
    }
}
//@@author

